containers:
  core:
    image: skiffos/skiff-core-gentoo:latest
    entrypoint: ["/lib/systemd/systemd"]
    # systemd: indicate this is a container
    env: ["container=docker"]
    stopSignal: RTMIN+3
    tty: true
    disableInit: true
    workingDirectory: /
    mounts:
      - /dev:/dev
      - /etc/hostname:/etc/hostname:ro
      - /lib/modules:/lib/modules:ro
      - /mnt:/mnt
      - /run/udev:/run/udev
      - /mnt/persist/skiff/core/repos/binpkgs:/var/cache/binpkgs
      - /mnt/persist/skiff/core/repos/distfiles:/var/cache/distfiles
      - /mnt/persist/skiff/core/repos/docker:/var/lib/docker
      - /mnt/persist/skiff/core/repos/gentoo:/var/db/repos/gentoo
      - /mnt/persist/skiff/core/repos/linux:/usr/src
      - /mnt/persist/skiff/core/repos/log:/var/log
      - /mnt/persist/skiff/core/repos/tmp:/var/tmp
    privileged: true
    startAfterCreate: true
    restartPolicy: "always"
    capAdd:
      - ALL
    hostIPC: true
    hostUTS: true
    hostNetwork: true
    securityOpt:
      - seccomp=unconfined
      - apparmor=unconfined
    tmpFs:
      /run: rw,noexec,nosuid,size=65536k
      /run/lock: rw,noexec,nosuid,size=65536k
users:
  core:
    container: core
    containerUser: core
    createContainerUser: true
    containerShell:
      - "/bin/bash"
    auth:
      copyRootKeys: true
images:
  skiffos/skiff-core-gentoo:latest:
    pull:
      # also an option: policy: ifbuildfails
      policy: ifnotexists
      # avoid docker hub rate limits
      registry: quay.io
    # uncomment to build on the device
    # build:
    #   source: /opt/skiff/coreenv/skiff-core-gentoo
